version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name kadai-test --s3-location s3://work-test-imamura/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src